### PR TITLE
This was a lot of work to get wide character support. I believe I

### PR DESCRIPTION
**Pull request by pkivolowitz**
have done it correctly BUT

Wide characters are displayed as two space blanks even though I
can prove they render properly with wcout.

Still, this is an improvement over not handling wide chars at all.

Someday, this will be fixed.

### CODE REVIEW

**Comment by LOZORD** [comment]
Is there any way to just support Unicode (which should encompass wide-chars), rather than just ASCII?

**Comment by pkivolowitz** [comment]
The wide character support is Unicode UTF-8 - that's all ncurses supports.

The database can be configured to store anything we want, I believe. I don't know what impact this would have on pas-core or on the rest of past. I haven't enough experience with "them furin types."

Do you know about that stuff or do we know someone we can ask?

**Comment by LOZORD** [comment]
Check out [this MySQL page](https://dev.mysql.com/doc/refman/5.7/en/charset-unicode.html).

I think we will run into issues with lines like [this](https://github.com/pas-audio-server/pas-schema/blob/master/create-paths.sql#L7). We will save ourselves a lot of headaches if our DB is consistent with the "view" of the input text. Debugging weird chars will be easier if we know that they are at least saved correctly in the database.

**Comment by pkivolowitz** [comment]
I am converting to UTF16 now.

**Comment by pkivolowitz** [comment]
Poop. I changed the database to UTF16 then looked into our strings in
proto3. They are only UTF8.

bytes are ASCII-8BIT.

https://developers.google.com/protocol-buffers/docs/proto3#scalar

**Comment by LOZORD** [comment]
So then we should just use bytes to be safe? As long as we interpret everything then as Unicode, then we should be ok. Also, Unicode will allow us to use Emojis 🎉

**Comment by pkivolowitz** [comment]
Not all UNICODE is the same, I'm saying. Apparently there is a translation
to UTF8 already happening (as the DB is now UTF16 and I can cout UTF8).

Just can't get ncursesw (the version that is supposed to do it) do it.

I think it will "just work" on the web.

**Pull request merged**
